### ISSUE TITLE
Launch client but nothing happend

### ISSUE THREAD

**Issue by ysilvela** [Wisembly/elephant.io#101]
Hi,

I launch a client but nothing happend after lauch. Mi client code:

$client = new Client(new Version1X('www.server.es:443/path'));
$client->initialize();
print_r($client,true);
$r = $client->read();
$client->close();

After few seconds I can see the next log:

Fatal error: Uncaught exception 'ElephantIO\Exception\ServerConnectionFailureException' with message 'An error occurred while trying to establish a connection to the server' in C:\Users\frameworks\elephant.io-3.0.0\src\Engine\SocketIO\Version1X.php:144

I test the connection using Javascript and it seems good.
And I download the last code. I'm already view that the code has the  #95 merge.

Thanks.

**Comment by Taluu** [comment]
The read method is flawed, see https://github.com/Wisembly/Elephant.io/issues/74#issuecomment-56103467, https://github.com/Wisembly/elephant.io/issues/115#issuecomment-139771843
