### ISSUE TITLE
Handshake fails if server restricts origins

### ISSUE THREAD

**Issue by vincentdieltiens** [Wisembly/elephant.io#102]
Hi,

I've a node socket.io server (using https) to which both JS and PHP clients connect.
Everything is fine until I restrict the server to some origins : the JS clients can connect but not the php anymore.

After some digging, I see that the handshake is failing because it uses `file_get_contents` without setting the origin. If I force the origin it seems to works correctly :

```php
$context['http'] = ['timeout' => (float) $this->options['timeout'], 'header' => 'Origin: https://some.domain.com'];
```

Maybe it's a good idea to also let the user to set the origin as an option (default to `*`) ? Something like :
```php
new ElephantIO\Client(
    new ElephantIO\Engine\SocketIO\Version1X(
        'https://my.server.com:12345?param1=value1',
        array('origin' => 'https://some.domain.com')
    )
);
```
In this case, the origin is properly set in the `handshake` and `upgradeTransport`
Vincent

**Comment by Taluu** [comment]
Seems not a bad idea, even though I don't think we should set a default. But we should allow to add some more context through http (such as adding headers) in the handshake, which is not currently the case...

**Comment by vincentdieltiens** [comment]
For my "urgent" needs, I've implemented the solution explained above (+ possibility to set the namespace) and confirm that is working.

It's not a bad idea to give more flexibility. This could give the possibility to use token based authentication (using headers)

Two questions :
* Do we need more flexibility than adding extra headers ?
* Should we give the possibility to set different extra headers for the `handshake` and the `upgradeTransport` ?

**Comment by Taluu** [comment]
The thing is, the "http" context is completely overwritten in the `handshake` method, which prevents it from being extended with additionnal headers... a replace should do the trick though.

I think the http context should also be used for the `upgradeTransport`, we hence need the generalization of this context, but now, how to store the headers is another question (an array ? an object ? a string which needs to manually build the headers parameters ?)

**Comment by vincentdieltiens** [comment]
I think we can forget the "string" for the headers : it's prone to errors.

The most obvious is an object. We can learn from the `HeaderBag` of the HttpFoundation (https://github.com/symfony/HttpFoundation/blob/master/HeaderBag.php) of symfony2 (or just import it using composer ?)

This could leads to this interface :
```php
$headers = new HeaderBag([
    'Origin' => 'https://some.domain.com',
    'Authorization' => sprintf('Bearer %s', $token)
]);
$client = new ElephantIO\Client(
    new ElephantIO\Engine\SocketIO\Version1X(
        'https://my.server.com:12345?param1=value1',
        ['headers' => $headers]
    )
);
```

We could do a test if the Engine constructor, if the 'header' option is an array, encapsulate it in a `HeaderBag` object.

**Comment by Taluu** [comment]
I don't think it should be in the root though, as this is really a (http) context option. But I think only an array or an object should be supported, not both (too much of a hassle to support both). And as I don't want to depend on the whole http foundation component only for the HeaderBag, its inclusion is a no go...

But copying it may be the way to go, supporting only this object then. But then, it would mean that I must be aware of this property (if it exists), and then transform it (whether it is not a string, which is, as you said, too prone to errors).

Or, another solution which is simple enough, as you showed it in your last message : leave the developper use whatever he wants, as long as it is in the correct format. It can then be a `HeaderBag`, a string, ... as long as it is valid with the context option, anything is fine, as long as the merge is correctly done for the handshake, as [the context is already used as is in the `upgradeTransport`](https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L178) through [the stream initialization](https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L57)

**Comment by vincentdieltiens** [comment]
> Or, another solution which is simple enough, as you showed it in your last message : leave the developper use whatever he wants, as long as it is in the correct format. It can then be a HeaderBag, a string, ... as long as it is valid with the context option

It's good idea. But I think that having a `HeaderBag` like class available in elephant IO is a good idea too.

> I don't think it should be in the root though, as this is really a (http) context option.

So, you mean something like this (or a string for `$headers`) ?

```php
$headers = new HeaderBag([
    'Origin' => 'https://some.domain.com',
    'Authorization' => sprintf('Bearer %s', $token)
]);
$context = [
    'http' => [
        'headers' => $headers
    ]
];
$client = new ElephantIO\Client(
    new ElephantIO\Engine\SocketIO\Version1X(
        'https://my.server.com:12345?param1=value1', [
            'context' => $context
        ]
    )
);
```
IMO, this have two drawbacks :
* the developer must be aware of the context options format. It makes the use of Elephant.io more complicated. 
* I agree that, from the point of view of the elephant.io implementation, it's a http context option, but if you see elephant.io as a black box,for the developper it's a websocket option regardless of the implementation of this black box : "I want those headers for my websocket connection"

(I hope that my frenchglish is understandable :D)

**Comment by Taluu** [comment]
I do get your point, but the thing is, the "options" parameters is not *only* options for the context... and also the context can vary from http. ssl, ... etc.

So I can't really bring these options on another level. But heh, it is an 'advanced usage" of Elephant.io, hence the developper knows what the hell he wants to do :D (okay, this is a false argument)

**Comment by vincentdieltiens** [comment]
AFAIK, socket.io is for websocket which is an upgrade of HTTP... This can be seen in elephant code IO : the http context is "forced"  :
https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L141
I personally don't see any reasons to support other contexts than HTTP.

I don't see the origin checks as an "Advanced usage" :D
Although I don't think that the choice of Socket.io to set default origin as "*" is a good one (but nothing to do in this conversation :))

**Comment by Taluu** [comment]
Well, I guess it should be the `url['scheme']` which should be the key for the context... Even though I'll need to check which context can be used. as it seems that 'http' is also the one for 'https'. Even though it is true that I don't think that the `handshake` should be done with anything else that http, but it is not the case for [the stream connection](https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L53-L55)

That is the difference between the `handshake` and the real "connection" through a socket... But maybe I can simplify the context, and put everything in there, and prefix with the correct scheme when I'm using it

**Comment by vincentdieltiens** [comment]
> But maybe I can simplify the context, and put everything in there, and prefix with the correct scheme when I'm using it

The scheme (ssl:// or tcp://) is a totally différent thing than the stream context.
We can use the same context for a secured and not secured connection.

So, I think that we can use the same $context for the handshake and the stream connection.

This could be good solution :
```php
$headers = new HeaderBag([
    'Origin' => 'https://some.domain.com',
    'Authorization' => sprintf('Bearer %s', $token)
]);
$httpContext = ['header' => $headers];
$client = new ElephantIO\Client(
    new ElephantIO\Engine\SocketIO\Version1X(
        'https://my.server.com:12345?param1=value1', [
            'context' => $httpContext
        ]
    )
);
```
Since the value *must* be "compatible" with the php stream context, in the implementation we just need to "extend" `$context['http']` array with the context given by parameter.


What do you think ?

**Comment by Taluu** [comment]
The thing is, we can still connect through ssl (not on the handshake, that's a given, but [on the socket connection](https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L53-L55)), and it looks like, as I read the docs on contexts, and [https wrappers does have the same options as http AND ssl wrappers](http://php.net/manual/en/context.ssl.php#refsect1-context.ssl-notes) as https is using ssl

So, this looks like to me that either http, either https should be used, and not only http. We can then use your solution, but just know which wrapper we should use.... and we have this information once the url to connect to is parsed, [which is done early](https://github.com/Wisembly/elephant.io/blob/master/src/Engine/AbstractSocketIO.php#L46). So no problems here to have only one context to rule them all (sorry, had to put this one here :3).

BTW, I think I should maybe check if the openssl is activated if a secured url is used, [as php needs it](http://php.net/manual/en/wrappers.http.php#refsect1-wrappers.http-notes) if we are using a secured url

**Comment by vincentdieltiens** [comment]
Ok, I get your point about 'http' or 'ssl' context.
But in fact, we can't use one context to rule the others. Because the 'ssl' context doesn't accept the same option (like 'header' as 'http' does).

So, we should keep the initial structure :
```php
[ 
    'context' => [
        'http' => [ ... ],
        'ssl' => [ ... ]
    ]
]
```
or using : 
```php
[
    'http_context' = [ ... ],
    'ssl_context' => [ ... ]
]
```

or forcing the developer to use the following methods `setHttpContext` and `setSSLContext`

**Comment by vincentdieltiens** [comment]
And what about creating 2 classes : SSLContext and HttpContext each with specific methods according to the options of each context ? (Like a `addHeader($header, $value)`

It's easy to use :)

**Comment by Taluu** [comment]
Thought about it, but I think this is a bit a currently bit too bit too nuch...

**Comment by vincentdieltiens** [comment]
Mmmh, I like this solution :
```php
$httpContext = new HttpContext();
$httpContext->addHeader('Origin', 'https://domain.com');

$client = new ElephantIO\Client(
    new ElephantIO\Engine\SocketIO\Version1X(
        'https://my.server.com:12345?param1=value1', [
            'http_context' => $httpContext
        ]
    )
);
```

because it's :
    1. easy to use
    2. explicit (better than implicit)
    3. If we define correctly the `HttpContext` and `SSLContext` classes, we can cast it : 
```php
$context['http'] = (array)$this->options['http_context'];
```
   That lets the possibility to use our context classes or arrays (which should be compatible with php stream context options).

**Comment by Taluu** [comment]
Sure, but once again, I think this is overkill, and this is not the goal of Elephant to have a full-fledged stream client or offer to use one. Elephant is just a lib that uses stream (instead of developping a solution around it) to communicate through websockets with another service.

**Comment by vincentdieltiens** [comment]
Alright, as you wish :)

**Comment by vincentdieltiens** [comment]
See the PR https://github.com/Wisembly/elephant.io/pull/103

**Comment by Taluu** [comment]
Fixed with latest merges and commits. :}

**Comment by Taluu** [comment]
@olukayodepaul Seriously, stop posting your problem (which isn't one, as php 5.4 is needed and you now have 5.3...) on random tickets.

Thanks.
