### ISSUE TITLE
SocketIO 1.x connect problem.

### ISSUE THREAD

**Issue by Padam87** [Wisembly/elephant.io#107]
Hi,

https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L182

Sometimes this exception is thrown, I cannot really figure out why... seems random. (The server is up, and even receives the emmitted data).

Any help would be much appreciated.

**Comment by Taluu** [comment]
What is the returned result ?

**Comment by Padam87** [comment]
Sorry for the delay, had to work on some other stuff yesterday.

I've found the problem, calling `initialize` twice on a client instance causes this exception.

```php
use ElephantIO\Client,
    ElephantIO\Engine\SocketIO\Version1X;

require __DIR__ . '/vendor/autoload.php';

$client = new Client(new Version1X('http://localhost:8888'));

while (true) {
    $client->initialize();
    $client->emit('broadcast', ['foo' => 'bar']);
    $client->close();
}
```

```
php socket.php
string(12) "HTTP/1.1 101"
string(0) ""

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The server returned an unexpected value. Expected "HTTP/1.1 101", had ""
```

**Comment by Taluu** [comment]
I see, and as there is a `isConnected` flag, I guess we could add a check on that flag, and do not reconnect if it is true

**Comment by Padam87** [comment]
The problem is that at that point, the `isConnected` flag is false, because `$client->close()` has been called, so connecting the second time is necessary. The socketio response is incorrent the second time. Is it possible that the connection is not closed properly?

I think I will only close connection in a destructor, that should solve my problem.

**Comment by Taluu** [comment]
I'm not quite sure that it should be enough, it must come from the socket sending an (awkwardly) empty message when trying to upgrade the transport... which is not what we should expect. [The `close()` method should send a `close` message](https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L75), but maybe it is not ever received ? Could you check that ? thanks

**Comment by Padam87** [comment]
Socketio receies the close message as expected, the problem was the session was not cleared when the connection closed. I guess socket.io remembers the session by id, and that is why upgradeTransport won't work for the second time.

**Comment by Taluu** [comment]
As your pr fixes it, I'm closing this ticket. Thanks !

**Comment by Manishbatra4** [comment]
i am facing same problem 

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The server returned an unexpected value. Expected "HTTP/1.1 101", had ""' in C:\wamp\www\socket\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 241


what to do

**Comment by Elysio** [comment]
Hello,
i am facing same problem too..

**Comment by ds40a** [comment]
Exactly the same problem.

**Comment by Satys** [comment]
I think this has been in Version2X, I was getting the same error Version1X, but when changed to Version2X, it works great.

**Comment by jeddey** [comment]
Exactly the same problem.

**Comment by elultimocapo421** [comment]
@Satys **Man, Thanks!!!!!**
