### ISSUE TITLE
listening events

### ISSUE THREAD

**Issue by wormen** [Wisembly/elephant.io#109]
tell me how to listen elephant.io event, similar in js
`
socket.on('foo', function (data) {
  });
`

**Comment by wormen** [comment]
that is, this library is interested in me as a server, not the client

**Comment by vincentdieltiens** [comment]
elephant.io is for building clients not servers.

**Comment by wormen** [comment]
I realized
Why not add support?

**Comment by vincentdieltiens** [comment]
Because it's not the purpose of this library.

**Comment by Taluu** [comment]
Hello,

the thing is, as @vincentdieltiens said it, this library is really specialized into broadcasting message as a client to a server. But, recently, a fix has been made for the read method of Socket.io implementations, so maybe this could help...

But, even though I'm repeating myself, this is not really the goal of this library. Closing.
