### ISSUE TITLE
CodeIgniter Autoload for third-party library

### ISSUE THREAD

**Issue by ccarlos009** [Wisembly/elephant.io#113]
Is there any way that I can integrate elephantio to CI?

**Comment by Taluu** [comment]
This library uses psr-4, so basically if you have a psr-r loader, you can use that lib. I need to add a message in the readme though, as suggested here http://stackoverflow.com/questions/27799591/elephant-io-client-not-working/28784075?noredirect=1#comment51475510_28784075

And then it is the basic usage (or more advanced, it's up to you). As i'm not familiar with CI, can't tell you how to use that though :(
