### ISSUE TITLE
Allow connection to ssl without verifying certificate

### ISSUE THREAD

**Issue by phict** [Wisembly/elephant.io#119]
Possibility to set ssl options not to verify certificates.
$context['ssl']["verify_peer"] = false;
$context['ssl']["verify_peer_name"] = false;

**Comment by Taluu** [comment]
It's already possible if you set the `context` option (cf https://github.com/Wisembly/elephant.io/blob/master/src/Engine/AbstractSocketIO.php#L51-L59), the content of the option is not verified, so you can actually set whatever you want in it.

Closing.

**Comment by phict** [comment]
Perfect!

 

Från: Baptiste Clavié [mailto:notifications@github.com] 
Skickat: den 8 oktober 2015 10:47
Till: Wisembly/elephant.io
Kopia: phict
Ämne: Re: [elephant.io] Allow connection to ssl without verifying certificate (#119)

 

It's already possible if you set the context option (cf https://github.com/Wisembly/elephant.io/blob/master/src/Engine/AbstractSocketIO.php#L51-L59), the content of the option is not verified, so you can actually set whatever you want in it.

Closing.
