### ISSUE TITLE
MalformedUrlException fails (v3.0)

### ISSUE THREAD

**Issue by mhassman** [Wisembly/elephant.io#123]
Hi, Interesting library. Thank you for creating it! :-)
Found one bug in AbstractSocketIO.php.. there's a missing use dependency - should include one for ElephantIO\Exception\MalformedUrlException. Without it, the exception will fail with not found.

**Comment by Taluu** [comment]
Could you make a PR ? thanks !

**Comment by mhassman** [comment]
Please verify this is correct. commit: 1eb2618.
Thnx!

**Comment by Taluu** [comment]
Looks good !

**Comment by lattwood** [comment]
Looks like this isn't in master/any tags

**Comment by Taluu** [comment]
Indeed, it's not. Care to make a PR ? :}
