### ISSUE TITLE
Please revise docs with example of client connecting and send a message and wait for response.

### ISSUE THREAD

**Issue by r3wt** [Wisembly/elephant.io#126]
I am emitting events like this:

``` php
public function emit($event,$data,$callback=false)
{
    $c = \App\Config::getInstance()['socketio'];
    $driver = new \ElephantIO\Client(
        new \ElephantIO\Engine\SocketIO\Version1X($c['endpoint']);
    );
    $driver->initialize();
    $driver->emit('authentication',$c['key']);
    $driver->emit($event,$data);
    if(is_callable($callback)){
        //wait for response and call callback with response
    }
    $driver->close();
}
```

It is evident that the documentation is incorrect, as i attempted to wait for a response using the sample code provided at your website, and the code looped forever, because there was not a response received.

**Comment by Taluu** [comment]
IIRC, the callback was not implemented on 3.0 (as we are not using this feature, we only send data and that's it). And the document (or the website...) is sadly not up to date.

PRs are welcome though.
