### ISSUE TITLE
Execution time 

### ISSUE THREAD

**Issue by danielb1987** [Wisembly/elephant.io#127]
Thank you for this great script!

The line:

`usleep((int) $this->options['wait']);`

in src/Engine/SocketIO/Version1X.php is slowing down the execution time. Is the usleep realy necessarily?

**Comment by guillaumepotier** [comment]
I recall we had to put it to avoid a premature connexion close that prevented to properly send the messages. By default we wait 100ms, I recall too we tested this default value and 50ms was the faster we could do having some transports failing.

You could try setting your own option to a value that works for you.

Hope that helps.

Best

**Comment by danielb1987** [comment]
Thanks for you quick reply!

I will try to figure out what the sweetspot is for our application. Is there no way of knowing when the connexion can be closed by any kind of callback?

**Comment by guillaumepotier** [comment]
Since we only used elephant to push data without a need to read from the server, we did not implement such a thing.

**Comment by Taluu** [comment]
(I am considering this solved, but indeed callbacks are not yet implemented in 3.0, cf #73)
