### ISSUE TITLE
SSL/https connection to nodeJS support

### ISSUE THREAD

**Issue by Zaszczyk** [Wisembly/elephant.io#129]
I need to run nodeJS and socket.io over ssl(wss and https). Does elephant.io support such connection? I mean php -> nodeJS over ssl. I didn't found any examples and only changing http to https not works. I got error:
```

This server does not support the websocket transport, aborting
/var/www/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:150
0
#0 /var/www/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake()
#1 /var/www/www/vendor/wisembly/elephant.io/src/Client.php(55): ElephantIO\Engine\SocketIO\Version1X->connect()
```

**Comment by guillaumepotier** [comment]
Hi @Zaszczyk 

Yes Elephant works with wss, we used that configuration in production. Dunno why you encounter this exception, could you paste more of your code and Elephant configuration?

Best

**Comment by Zaszczyk** [comment]
Sure, thanks for quick answer. This is elephant:
```
$this->client = new Client(new Version1X('https://localhost:5276'));
$this->client->initialize();
$this->client->emit($channel, $package);
$this->client->close();
```
socket.io:
```
var server;
var env,
    io,
    logger,
    port = 5276;

logger = require('winston');

    env = 'wss';
    var fs = require('fs');

    var options = {
        key: fs.readFileSync('ssl/server.key'),
        cert: fs.readFileSync('ssl/server.cert'),
        ca: fs.readFileSync('ssl/ca.crt')
    };

    server = require('https').createServer(options)
    logger.info('wss run');


io = require('socket.io')(server, {
    path: '/socket.io'
});


io.on('connection', function (socket) {
    logger.info('SocketIO > Connected socket ' + socket.id);

    var room = socket.handshake.query.sessionId;
    if (room !== undefined) {
        socket.join(room);
        if (env == 'ws') {
            logger.info('SocketIO > Joined to room ' + room);
        }
    }

    socket.on('pushNotification', function (package) {
        for (key in package.toSessionIds) {
            io.to(package.toSessionIds[key]).emit('pushNotification', package.data);
            if (env == 'ws') {
                logger.info('SocketIO > send notification ' + JSON.stringify(package.data) + ' to ' + package.toSessionIds[key]);
            }
        }
    });

    socket.on('disconnect', function () {
        if (env == 'ws') {
            logger.info('SocketIO > Disconnected socket ' + socket.id);
        }
    });
});


server.listen(port);

/** ERRORS **/
process.on('uncaughtException', function (err) {
    console.log(err);
});

io.on('error', function (err) {
    console.log(err);
});
```

**Comment by guillaumepotier** [comment]
I dunno for the nodejs part, but our elephant config seemed the same, except we run it on port `443` which is the standard https port, dunno if it could affect things to run it on another port (we supposed user won't block 443 and  80 ports but could totally block all the others, less risky and more standard). Maybe could be that ? Have you tried to connect to wss with a js client to test if problem is not on node server?

Best

**Comment by Zaszczyk** [comment]
However i Have Apache and nodeJS at this same server, so 443 is reserved for Apache right? Socket.io client connects with server without any problems

**Comment by guillaumepotier** [comment]
> However i Have Apache and nodeJS at this same server, so 443 is reserved for Apache right?

**Comment by Zaszczyk** [comment]
@guillaumepotier I resolved that by disabling SSL in localhost connection, it is unnecessary there:

```
$this->client = new Client(new Version1X('https://localhost:5276', [
            'context' => [
                'ssl' => [
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                ]
            ]
        ]));
```
However I had huge problem to disable verify_peer, I found it was caused by old version elephant.io in composer repository. I had to create own fork and add it to composer repo. You should create release to composer repo/packgaist.

**Comment by Taluu** [comment]
> However I had huge problem to disable verify_peer, I found it was caused by old version elephant.io in composer repository. I had to create own fork and add it to composer repo. You should create release to composer repo/packgaist.

What do you mean ? If it's an old version of elephant, it is available on composer : https://packagist.org/packages/wisembly/elephant.io#v2.0.4

Unless I misunderstood something (Which is highly probable)

**Comment by Zaszczyk** [comment]
In composer I was using v3.0.0. which is little old, newer version is dev-master, but it isn't recommended to user dev-master. So I had to make fork of master and add my fork to composer. I just think You should make new stable release :)

**Comment by Taluu** [comment]
Oh. Indeed, I will make a release then when I'll have some time (probably next week) then (I'll need to review the changes first, I may have forgotten 90% of them haha)

**Comment by Taluu** [comment]
3.1 was released just today (I forgot about it, sorry) : https://github.com/Wisembly/elephant.io/releases/tag/3.1.0
