### ISSUE TITLE
New release any time soon? :(

### ISSUE THREAD

**Issue by circuuz** [Wisembly/elephant.io#131]

**Comment by Taluu** [comment]
Hello,

As I indicated here : https://github.com/Wisembly/elephant.io/issues/129#issuecomment-194981492 I will try to do it this week or the next. Should be a 3.1, as IRC there are now namespaces support and a bunch of other improvements, but I need to refresh my memory first !

**Comment by Taluu** [comment]
Sorry for the delay, it was released : https://github.com/Wisembly/elephant.io/releases/tag/3.1.0
