### ISSUE TITLE
Error trying to access to namespaces with "of" method

### ISSUE THREAD

**Issue by coffeeontie** [Wisembly/elephant.io#132]
I am using Elephant to emit some data to a socket (0.9 version).
So I used the example attached to the repo (customizing namespace and port), but it gives me a fatal error: "call to undefined method ElephantIO\Client::of().

**Comment by Taluu** [comment]
Are you using dev-master in your composer (if you are using composer) ? Or the 3.0.0 ?

If it is the 3.0.0, it is normal, as this should be a 3.1 feature (which reminds me I need to release it...)
