### ISSUE TITLE
Sending token (for JWT) to scoket.io server

### ISSUE THREAD

**Issue by frey1esm** [Wisembly/elephant.io#133]
Is it possible to add a query parameter when connecting to a socket.io server, so that client can be [authenticated (via JWT)](https://github.com/auth0/socketio-jwt)?

In a javascript client, it is as easy as:

```
var socket = io.connect('http://localhost:9000', {
  'query': 'token=' + your_jwt
});
```

**Comment by Taluu** [comment]
Hum, IRC, you can connect with a query string on the address `http://localhost:9000/?query=<jwt>`, no ?

**Comment by weapy** [comment]
This is working, i use:
`$socket = new ElephantIO\Client(new \ElephantIO\Engine\SocketIO\Version1X("https://server.com:3000" . '/?socketController=thevalueyouwanthere'));
$socket->initialize();
$socket->emit('event', $data);`
And on the serve side on connection:
`client.handshake.query` will have `socketController` key.
client is: `io.on('connection', function (client) {`

This issue can be closed.
