### ISSUE TITLE
Emit json is not validate

### ISSUE THREAD

**Issue by salvatorelapi** [Wisembly/elephant.io#139]
When emit message, return a json that is not valid. If use your exampe code:
$client->emit('broadcast', ['foo' => 'bar']);  generate this invalid json {foo: 'bar'}. Problem is inside Encoder probably

**Comment by Taluu** [comment]
Looking at https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L91, I don't see a reason why such a json would be generated. Could you look at the result of `json_encode(['broadcast', ['foo' => 'bar'])` ? thanks.
