### ISSUE TITLE
Catchable fatal error: Argument 1 passed to ElephantIO\Client::__construct() must be an instance of ElephantIO\EngineInterface

### ISSUE THREAD

**Issue by kaddyadriano** [Wisembly/elephant.io#140]
Catchable fatal error: Argument 1 passed to ElephantIO\Client::__construct() must be an instance of ElephantIO\EngineInterface, string given,...

I have used this code

```php
use ElephantIO\Client as Elephant;

$elephant = new Elephant('http://localhost:3000', 'socket.io', 1, false, true, true);

$elephant->init();
$elephant->send(
    ElephantIOClient::TYPE_EVENT,
    null,
    null,
    json_encode(array('name' => 'messageSent', 'args' => 'bar'))
);
$elephant->close();
```

**Comment by krichprollsch** [comment]
Hello,

Thank you for your report, but as explained into the error, you must use an `EngineInterface` to create a new client.
Please take a look here to have an example : https://github.com/Wisembly/elephant.io/blob/master/example/socket.io/1.x/emitter/client.php#L17

**Comment by Taluu** [comment]
(closing as everything is in the samples)

**Comment by kaddyadriano** [comment]
I have done it exactly as shown in the example now I am getting this error:
`Fatal error: Uncaught exception 'ElephantIO\Exception\ServerConnectionFailureException' with message 'An error occurred while trying to establish a connection to the server'`
I am trying to understand what the problem is. Do I need to install anything on my server in order for this to work? Please let me know. Thanks!

**Comment by krichprollsch** [comment]
Do you have a websocket server installed somewhere?
Elephant.io is only the client part, you need a websocket server.

**Comment by Taluu** [comment]
The server side is also in the samples : 
- https://github.com/Wisembly/elephant.io/blob/master/example/socket.io/1.x/emitter/server.js

You need to do a `npm install` and then a `npm start` first though

**Comment by kaddyadriano** [comment]
Thank you so much . I got it to work with the server side. I am now struggling to get socket.io to work in my cordova app. Any help is appreciated.
