### ISSUE TITLE
won't emit multiple concurrent requests

### ISSUE THREAD

**Issue by amraei** [Wisembly/elephant.io#142]
PHP code:

```
$server = new Elephant(new Version1X('http://localhost:2020'));

$i = 0;
while($i++ < 10){
    $server->emit('myevent', ['id'=>$i]);
}
```

NodeJS server:

```
var io = require('socket.io')();
io.on('connection', function(socket){
    socket.on('myevent', function(data){
        console.log(data); 
        // Will be executed just one time {id: 1}
    });
});
io.listen(2020);
```

As I have `while($i++ < 10)`, it will be exexuted 10 times but in the server side (NodeJS) it just logs the event one time.

Is that regular? Am I missing something? How to make it enable to emit multiple requests?

**Comment by Taluu** [comment]
no, this isn't regular... There is a `usleep` on the `emit` call, that prevents the socket to be flooded (which in this case should make your case "regular" if there was no sleep)...

Try to increase the wait time ? It's an option in the engine.
