### ISSUE TITLE
Can't connect to the server when using SSL

### ISSUE THREAD

**Issue by eldan88** [Wisembly/elephant.io#147]
Hi, 

 I keep getting this issue everytime I try connecting using the SSL. But it works fine without SSL. 

ElephantIO\Exception\ServerConnectionFailureException. I am using the following code

```

       $client = new Client(new Version1X("https:://www.mydomainname.com:3000"));
        $client->initialize();
        $client->emit("test", ["key"=> "val"]);
        $client->close();

```

Any helpp would be really appreciated.

**Comment by guillaumepotier** [comment]
Hi there,

2 maybe silly points but:

- have you correctly `openssl` installed?
- Since you seem to run your https on non standard `443` port, did you check that your server could reach port `3000`?

Finally, do you have the message of the `ServerConnectionFailureException` thrown?

Best

**Comment by eldan88** [comment]
Hi,

Thanks for the fast reply. I am not using open SSL on my production server. I am using Comodo SSL. When I connect through the client it work(Code shown below)

When I use elephant.io only on https it keeps giving me an error message. I did a try catch and I keep getting the error message 

 An error occurred while trying to establish a connection to the server

My server Is working fine with port 3000... 

Have you tried testing elephant.io on an https protocol?


**My client code that is working fine**
```

       var socket = io.connect( 'https://mydomain.com:3000' );
        socket.on("connect",function () {

          /// console.log("test");
                socket.emit("new_order", {
                    new_order: "test"

                });
        });

```

**Comment by eldan88** [comment]
This is my server.js file

`var socket  = require( 'socket.io' );
var express = require('express');
var fs       = require("fs");
var app     = express();
var https  = require('https');
var http  = require('http');

var HTTPS_PORT = 3000;
var HTTP_PORT = 3001;

// HTTPS
var secureServer = https.createServer({
    key: fs.readFileSync('ssl.key'),
    cert: fs.readFileSync('ssl.crt')
  }, app).listen(HTTPS_PORT, function () {
    console.log('Secure Server listening on port ' + HTTPS_PORT);




  });

  var io      = socket.listen( secureServer );


    io.sockets.on('connection',function (socket) {

    //console.log("user connect");

    socket.on("new_order",function (data) {

        io.emit("new_order",data);
        console.log(data);

    });



});
`

**Comment by guillaumepotier** [comment]
When I was talking of `openssl` it is not the ssl you have installed on your production, but the PHP package you'll need on the server running elephant ! I recall its uses `openssl_encrypt` somewhere and needs it to be installed. [more info here](http://php.net/manual/en/book.openssl.php)

**Comment by eldan88** [comment]
I have open ssl on my production server. I even tested to make sure by running php -m | grep -i openssl and it returned openssl

**Comment by eldan88** [comment]
I used openssl_encrypt in my production server just to double check openssl is wokring, and it seems to be working. So it doesn't seem to be an openssl issue. 

Have you personally tried using your code with an SSL connection on php 5.6? 


**This is what I used**
```
$string = 'It works ? Or not it works ?';
$pass = '1234';
$method = 'aes128';

 openssl_encrypt ($string, $method, $pass);
```

**Comment by Taluu** [comment]
Hi,

Do you have a valid ssl certificate on your server ? Could you run the following code :

```php
<?php

$w = stream_get_wrappers();
echo 'openssl: ',  extension_loaded  ('openssl') ? 'yes':'no', "\n";
echo 'http wrapper: ', in_array('http', $w) ? 'yes':'no', "\n";
echo 'https wrapper: ', in_array('https', $w) ? 'yes':'no', "\n";
echo 'wrappers: ', var_export($w);
```

And tell me the output ?

Another thing to try, would be to add the following to the contexts  :

```
      "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false,
        ),
```

To do so, you need to make this array into `$options['context']` when instantiating the engine :

```php
<?php

$options = [
    'context' => 'ssl' => [
        'verify_peer' => false,
         'verify_peer_name' => false
];

$engine = new Version1X($url, $options);
```

**Comment by kamyab-beygi** [comment]
I have same this problem and it didn't work well :(( 
I ran that code these are my result :  
openssl: yes http wrapper: yes https wrapper: yes wrappers: array ( 0 => 'https', 1 => 'ftps', 2 => 'compress.zlib', 3 => 'php', 4 => 'file', 5 => 'glob', 6 => 'data', 7 => 'http', 8 => 'ftp', 9 => 'phar', )
and this is my rest of the code :

$socket = "https://nodemakeseverythingrealtime.khattokhat.com:3000";

          $options = [
              'context' => [
                  'ssl' => [
                      'verify_peer' => false,
                       'verify_peer_name' => false
                  ]
              ]
          ];

        $client = new Client(new Version1X($socket,$options));
        $client->initialize();
        $client->emit("test", ["key"=> "val"]);
        $client->close();

**Comment by eldan88** [comment]
@Taluu 

Thank you for the response. I have passed the 
      $options = [
          'context' => [
              'ssl' => [
                  'verify_peer' => false,
                   'verify_peer_name' => false
              ]
          ]
      ];

to the Version1X class and it worked! 

I really appreciate your help!

**Comment by Taluu** [comment]
@kamyab-beygi Do you still have a `ServerConnectionFailure` exception, despite adding the context to the engine's options ?

@eldan88 Glad to hear it. :} This meant that if you are giving a SSL Certificate, it is not valid per se (these options tells curl to ignore if the ssl certficate is not valid (cf http://php.net/manual/en/context.ssl.php), and I think this is not safe ; that's why this isn't a default)

**Comment by eldan88** [comment]
@Taluu  Okay got it! Thanks for that explanation!

**Comment by kamyab-beygi** [comment]
Thank u so much I solved my problem , I had to use "HTTPS://localhost:3000" for my socket connection by the way :) Much appreciate it
