### ISSUE TITLE
Emitter via HTTPS

### ISSUE THREAD

**Issue by paulprok** [Wisembly/elephant.io#150]
I try to sent to:

```php
<?php
$client = new Client(new Version1X('http://sitename:7999'));
```

It's ok

But I try:

```php
<?php
$client = new Client(new Version1X('https://sitename:7999'));
```

And get the exception.

```
Warning: in_array() expects parameter 2 to be array, null given in \project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 172

Fatal error: Uncaught ElephantIO\Exception\UnsupportedTransportException: This server does not support the websocket transport, aborting in \project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php:173 Stack trace: #0 \project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake() #1 \project\vendor\wisembly\elephant.io\src\Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect() #2 \project\elephant.php(20): ElephantIO\Client->initialize() #3 {main} thrown in \project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 173
```

**Comment by Taluu** [comment]
Looks like the client cannot upgrade the transport to websocket (it doesn't even return the `upgrades` key). That is strange that this happens only on https though...

**Comment by Taluu** [comment]
Could you try to add a debug dump on `$decoded` after the line 170 in `Version1X.php`, and paste here what it returns ? Thanks

**Comment by paulprok** [comment]
Maybe helps server code:
```
var fs = require('fs');
var cfg = JSON.parse( fs.readFileSync('cfg.json'));
var https = require('https');
var express = require('express');
const opts = { key: fs.readFileSync(cfg.key), cert: fs.readFileSync(cfg.cert) }
var server = https.createServer(opts, function(req, res) {
	res.writeHead(200, { "Content-Type": "text/html" });
});
var io = require('socket.io').listen(server);
server.listen(cfg.port);
io.sockets.on('connection', function(socket) {
	console.log(socket.id);
});
```

now error is:
> Fatal error: Uncaught ElephantIO\Exception\ServerConnectionFailureException: An error occurred while trying to establish a connection to the server in project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php:167 Stack trace: #0 project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake() #1 project\vendor\wisembly\elephant.io\src\Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect() #2 project\elephant.php(22): ElephantIO\Client->initialize() #3 {main} thrown in project\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 167

so dump at the line 170 is empty

dump $url from line 163:
"https://project:7999/socket.io/?use_b64=0&EIO=2&transport=polling"

dump $result from line 164:
bool(false)

**Comment by Taluu** [comment]
Remove the `@` in front of the `file_get_contents` call on line 164, it should pop you an error

**Comment by paulprok** [comment]
html code where I get emits, that works:

```
<script src="//project:7999/socket.io/socket.io.js"></script>
<script>
var socket = io.connect('//project:7999', { query: 's=12345' });
...
```

I sending emits from html form via js, it's ok.

**Comment by paulprok** [comment]
```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in project\protected\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 164
Warning: file_get_contents(): Failed to enable crypto in project\protected\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 164
Warning: file_get_contents(https://project:8999/socket.io/?use_b64=0&EIO=2&transport=polling): failed to open stream: operation failed in project\protected\vendor\wisembly\elephant.io\src\Engine\SocketIO\Version1X.php on line 164

```

**Comment by Taluu** [comment]
Could you try when instantiating the client to pass the following option :

```
$client = new Client(new Version1X('https://sitename:7999', ['context' => ['ssl' => ['verify_peer_name' =>false, 'verify_peer' => false]]]));
```

This should disable the certification verification (this kind of error is often due to this)

**Comment by paulprok** [comment]
Hooooray!
Issue is resolved =)
Thanks

**Comment by Taluu** [comment]
This should be handled and documented...

**Comment by paulprok** [comment]
> The docs are not written yet
said https://github.com/Wisembly/elephant.io =)

**Comment by ashikjyothi** [comment]
I tried connecting to my local server
`$client = new Client(new Version1X('http://localhost:3001'));`

And got this error

`ElephantIO\Exception\ServerConnectionFailureException: An error occurred while trying to establish a connection to the server in /var/www/html/Socket/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:167 Stack trace: #0 /var/www/html/Socket/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake() #1 /var/www/html/Socket/vendor/wisembly/elephant.io/src/Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect() #2 /var/www/html/Socket/emit_test.php(47): ElephantIO\Client->initialize() #3 {main}`

**Comment by Taluu** [comment]
https://github.com/Wisembly/elephant.io/issues/150#issuecomment-281318884

**Comment by ashikjyothi** [comment]
yeah tried that too...
here is my receiver html file
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="//localhost:3001/socket.io/socket.io.js"></script>
	<title>Title</title>
</head>
<body>
<script>
	var socket = io.connect('//localhost:3001', { query: 's=12345' });
	
	socket.on("new_order",function(data){
		console.log(data);
	})
</script>
</body>
</html>
```
But getting the same error

**Comment by Guley** [comment]
> ```
> <?php
> $client = new Client(new Version1X('https://sitename:7999', ['context' => ['ssl' => ['verify_peer_name' =>false, 'verify_peer' => false]]]));
> ```
***Here is what i try:***
```
$options = [
    'headers' => [
    	'token: xxxx',

    ],
    'context' => [
        'ssl' => [
            'verify_peer' => false,
            'verify_peer_name' => false
        ]
    ]
];


$client = new Client(new Version2X('https://xxx.xx.xx.xx:3000',$options));
```
Enable to send `token` in headers with above code. Is there any solution??
