### ISSUE TITLE
Unable to connect to my server

### ISSUE THREAD

**Issue by SteevyTheGeek** [Wisembly/elephant.io#153]
I have an Api Rest in symfony. I wanna push some message with Elephant but evrey time di try to connect symfony to my Server Node, it returns this message
`{"code":500,"message":"An error occurred while trying to establish a connection to the server"}`

Here is my symfony code:

```php
<?php

/**
   * @Rest\View()
   * @Rest\Get("/users")
*/
public function listerLesUtilisateursAction( Request $request ){

    $client = new Client(new Version1X('http://battle-push-test.webmobilexpert.com'));
		
    $client->initialize();
    $client->emit('test', ['foo' => 'bar']);
    $client->close();		
    return true;
        
}

```
Here is my server code:

```javascript
var app = require( 'express' )();
var server = require( 'http' ).createServer( app );
var io = require( 'socket.io' ).listen( server );

var port = process.env.PORT || 8080;


app.get('/', function (req, res) {
  res.end("Server works fine" );
});

io.sockets.on( 'connection', ( socket ) => {
    
   //Wen client connects, send a test message
    socket.on( 'test', ( datas ) => {
        socket.broadcast.emit( 'connect_message', 'Vous êtes connecté au serveur push avec succès wi' );

    });
});
```

Help me please, it's two weeks that i try to resolve this :(

**Comment by SteevyTheGeek** [comment]
No help please?

**Comment by Taluu** [comment]
The port looks wrong (by default you are expecting it to be on 8080, but on the server url in the php code, it fallbacks on 80.... you need to add `:8080` to your url,this should be fine)

**Comment by SteevyTheGeek** [comment]
Ok.. i will try this

**Comment by SteevyTheGeek** [comment]
Nothing works. Return the same error:

`{"code":500,"message":"An error occurred while trying to establish a connection to the server"}`

**Comment by Taluu** [comment]
What happens if you try `curl http://battle-push-test.webmobilexpert.com`, and `curl http://battle-push-test.webmobilexpert.com:8080` ?

**Comment by SteevyTheGeek** [comment]
When i run :
`curl http://battle-push-test.webmobilexpert.com`
this return to me the good message:
`Server works fine`

but `curl http://battle-push-test.webmobilexpert.com:8080` gives to an error connection:
` Failed to connect to battle-push-test.webmobilexpert.com port 8080: Timed out`

**Comment by SteevyTheGeek** [comment]
You let me down dear friend!!! :(

**Comment by guillaumepotier** [comment]
Hi @SteevyTheGeek 

IMHO your node code looks wrong. You're not specifying anywhere your port for express nor socket.io. I suspect they run on default 80 port when none given.

Have you tried to connect **frontend** with socket.io javascript client, before saying Elephant is not working? Elephant should allow you to connect through your PHP **as the frontend javascript client does**. If your frontend client has the same problem, it might be a node backend related issue.

Furthermore, even if we like to help here, Stackoverflow would be a much better place to ask your question.

Hope that helps

Best

**Comment by SteevyTheGeek** [comment]
I didn't copy the whole code.. Sorry. But i am listen to 8080 on localhost.

Yes i test, and my client connects wihtout any problem to the Node Server. i don't know why my restFull Api can't connect

**Comment by SteevyTheGeek** [comment]
No idea about what's wrong?

**Comment by guillaumepotier** [comment]
No we do not have any idea about what's wrong, sorry.

I think we spent both Taluu and I enough time to understand what's going wrong here and we won't go deeper on this issue.

If you provide us php errors, node logs, that shows **clear evidence** that there is a bug on our side, we'll re-open this issue and fix it.

Meanwhile, try to ask better help on Stackoverflow or elsewhere to help you provide these evidences to us;

Best and good luck !
