### ISSUE TITLE
The server returned an unexpected value. Expected "HTTP/1.1 101", had ""

### ISSUE THREAD

**Issue by therock115** [Wisembly/elephant.io#157]
Hello all,

I've searched around for a solution for the error 'The server returned an unexpected value. Expected "HTTP/1.1 101", had ""'. My php file is as follows

include("/vendor/autoload.php");

use ElephantIO\Client as Client;
use ElephantIO\Engine\SocketIO\Version1X as Version1X;

$version = new Version1X("http://localhost:3001");

$client = new Client(new Version1X("http://localhost:3001", ['context' => ['ssl' => ['verify_peer_name' =>false, 'verify_peer' => false]]]));

	$client->initialize();
	$client->emit("data_emit", ["var1"=>"hello", "var2"=>"world"]);
	$client->close();

Any help with this error would be greatly appreciated.

Thanks.

**Comment by kilab** [comment]
Try change **Version1X** to **Version2X**.

It resolved my problem.

**Comment by eGirlAsm** [comment]
i have same problem

**Comment by Taluu** [comment]
See #161
