### ISSUE TITLE
Getting error while trying to connect to a node server in php

### ISSUE THREAD

**Issue by ashikjyothi** [Wisembly/elephant.io#161]
I am trying to connect to a node server using ElephantIO in php
Here is the code

```
<?php
error_reporting(E_ALL);
ini_set('display_errors','On');

    use ElephantIO\Client,
        ElephantIO\Engine\SocketIO\Version1X,
        ElephantIO\Exception\ServerConnectionFailureException;

    require __DIR__ . '/vendor/autoload.php';

    $client = new Client(new Version1X('http://localhost:3001'));

    try
    {
        $client->initialize();
        $client->emit('new_order', ['foo' => 'bar']);
        $client->close();
    }
    catch (ServerConnectionFailureException $e)
    {
        echo $e;
    }
```
And its not connecting and is throwing an error

`ElephantIO\Exception\ServerConnectionFailureException: An error occurred while trying to establish a connection to the server in /var/www/html/Socket/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:167 Stack trace: #0 /var/www/html/Socket/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake() #1 /var/www/html/Socket/vendor/wisembly/elephant.io/src/Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect() #2 /var/www/html/Socket/emit_test.php(47): ElephantIO\Client->initialize() #3 {main}`

**Comment by Taluu** [comment]
As I said before, remvoe the `@` on the `file_get_contents` line (around line 167) in Version1X.php. If nothing prints out, set your error_display so that warnings are emitted (`error_reporting(E_ALL);` on your code, if memory serves me right).

You should have more info on the error.

**Comment by ashikjyothi** [comment]
Ok now its fixed.
So what do you put the @ symbol in the first place?
Can fix this issue in a later version ryt

**Comment by ashikjyothi** [comment]
Again getting error on connection 

Fatal error: Uncaught ElephantIO\Exception\ServerConnectionFailureException: An error occurred while trying to establish a connection to the server in /var/www/html/Socket2/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php on line 167

**Comment by EmmanuelBeja** [comment]
replace `$client = new Client(new Version1X('http://localhost:3001'));` with `$client = new Client(new Version2X('http://localhost:3001'));`

**Comment by EmmanuelBeja** [comment]
and ` ElephantIO\Engine\SocketIO\Version1X,` with ` ElephantIO\Engine\SocketIO\Version2X,`

**Comment by Taluu** [comment]
I'll try to do something to have a clearer message then...

**Comment by Taluu** [comment]
Please try #162 and do a `$e->getErrorMessage()` to check what is wrong. This should point you in the right direction (IMO, you should try `Version2X` instead of `Version1X` as suggested by @EmmanuelBeja)
