### ISSUE TITLE
Can't connect Elephant with Node (but works on local environment)

### ISSUE THREAD

**Issue by jcarbad** [Wisembly/elephant.io#163]
When I try to connect to the Node server with Elephant.io, I get the **ServerConnectionFailureException** when I call the _$client->initialize()_.  Browser clients can connect appropietely and Node is indeed sending the right JSON for assigning the socket, but PHP just fails.

Curiously, this doesn't happens in my local environment.

Please help, @Taluu

**Comment by Taluu** [comment]
Hi,

Are you using the latest version (3.3.1) ? There should be more information when this information occurs...

**Comment by jcarbad** [comment]
Man, I just solved the problem checking on several previews Issues. Thanks for the quick response!

**Comment by Taluu** [comment]
Let me guess : Using Version 1X instead of 2X ? :}

**Comment by jcarbad** [comment]
Exactly that. I followed an old tutorial. But, seriously, thanks mon ami!

**Comment by agueroveraalvaro** [comment]
@Taluu Thanks soo much really you saved me :1st_place_medal: !! there is a lof of people with the same issue, @jcarbad you must be more collaborative with the other developers :)

**Comment by Surfable** [comment]
1. Check ports (e.g. 80:8080; 443:8443) => `$client = new Client(new Version2X('https://server_node:8443'));`
2. Check self-asigned ssl/tls => `['context' => [
    'http' => [
      'method' => 'GET'
    ],
    'ssl' => [
      'verify_peer' => true,
      'allow_self_signed'=> true
    ]
  ]` as 2nd Param of `Version2X()`
3. Make sure php.ini has allow_url_fopen On
