### ISSUE TITLE
Cannot be establish the connection with server

### ISSUE THREAD

**Issue by hugohenrique** [Wisembly/elephant.io#165]
I'm not able to establish a connection to the server using this php client.
With the javascript client I usually get it.

```An error occurred while trying to establish a connection to the server``` relates #163 #161 #160 

I've been using port 3000 on the server.

**Comment by Taluu** [comment]
Do you have more information ? The exception should be more verbose now.

**Comment by hugohenrique** [comment]
<img width="1000" alt="screen shot 2017-11-20 at 16 39 58" src="https://user-images.githubusercontent.com/4316743/33037838-8293edba-ce11-11e7-9c64-8655160bccdb.png">
<img width="996" alt="screen shot 2017-11-20 at 16 39 49" src="https://user-images.githubusercontent.com/4316743/33037839-82c9e85c-ce11-11e7-8dbb-48805584d305.png">
<img width="1000" alt="screen shot 2017-11-20 at 16 39 41" src="https://user-images.githubusercontent.com/4316743/33037840-82ea743c-ce11-11e7-9d72-9da153b7e67b.png">
<img width="1013" alt="screen shot 2017-11-20 at 16 38 45" src="https://user-images.githubusercontent.com/4316743/33037800-6051259c-ce11-11e7-80a1-2f0fc61bc648.png">

**Comment by Taluu** [comment]
I'm suspecting you should use the `Version2X` instead of `Version1X` (as it is told in the tickets you linked). Anyway, more information should be available in the `getErrorMessage` method of the `ServerConnectionFailureException` class, which is thrown on this error.

**Comment by hugohenrique** [comment]
I'm already using the ```Version2X``` class and now I've added a try/catch and the ```getErrorMessage``` method is returning ```null```.

**Comment by Taluu** [comment]
Which version are you using ? Because the line 190 is not the one throwing the exception on latest tag and master...

Otherwise, could you add a sort of dump of the `$error` variable just before the exception is thrown ? Thanks.

**Comment by hugohenrique** [comment]
I try with ```dev-master``` version

**Comment by hugohenrique** [comment]
Removing the ```@``` in ```@file_get_contents...``` line 177 ```Version1X.php```
I received this warning:
```
Warning: file_get_contents(http://127.0.0.1:3000/socket.io/?use_b64=0&amp;EIO=3&amp;transport=polling): failed to open stream: Connection refused
```

**Comment by Taluu** [comment]
Try to access `http://127.0.0.1:3000/socket.io/?use_b64=0&amp;EIO=3&amp;transport=polling` then `http://127.0.0.1:3000/socket.io/?use_b64=0&EIO=3&transport=polling` ? In your given uri (in the construct), what is the value of the given url ?

**Comment by hugohenrique** [comment]
The error was not in the lib but in my network.
Sorry and thanks for your attention. @Taluu.

**Comment by Taluu** [comment]
Np. But reopening as it brought an error to my attention. :)

**Comment by prasitnarkdee** [comment]
I try to emit to https protocol then found error like this issue, for reference https://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more

i edit elephant.io/src/Engine/SocketIO/Version1X.php
`
# add
$this->context = array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);  
# before line 65
$this->stream = stream_socket_client($host, $errors[0], $errors[1], $this->options['timeout'], STREAM_CLIENT_CONNECT, stream_context_create($this->context));

# add
$context = array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);  
# before line 177
$result = @file_get_contents($url, false, stream_context_create($context));`

**Comment by Surfable** [comment]
I had the same issues. There is more then one pitfall btw. In my case docker container had a wrong port alignment. So: check ports in case of docker (e.g https://server_node:8443) But also a self-asigned tls/ssl can couse trouble. Use this workaround  `
        $context = [
          'http' => [
            'method' => 'GET'
          ],
          'ssl' => [
            'verify_peer' => true,
            'allow_self_signed'=> true
          ]
        ];
` @ stream_context_create()

But also your php.ini may need some more flags. Make sure allow_url_fopen is On

**Comment by SeinopSys** [comment]
This is usually caused by connection errors that gets eaten by the `@file_get_contents` line. The best would be to handle them instead.

**Comment by nidheesh1994** [comment]
I am getting the same issues. It caused after I switched from http to https

**Comment by lorenzyannick** [comment]
try https://github.com/Wisembly/elephant.io/issues/181#issuecomment-580669128

**Comment by bh013** [comment]
may help you

comment lines `164` ~ `174` in `/Engine/SocketIO/Version1X.php`

then write this code

```
$protocol = true === $this->url['secured'] ? 'ssl' : 'http';

if(isset($this->context[$protocol])){
    $context = $this->context;
    $context['http']=$context[$protocol];
    @unset($context['ssl']);
}
$context['http'] = $context['http'] ?? [];

if (isset($this->options['headers'])) {
    $headers = $context[$protocol]['header'] ?? [];
    $context['http']['header'] = array_merge($headers, $this->options['headers']);
}
if (isset($this->options['ssl'])) {
    $ssl = $context[$protocol]['ssl'] ?? [];
    $context['ssl'] = array_merge($ssl, $this->options['ssl']);
}
```

**Comment by seyitahmettanriver** [comment]
> may help you
> 
> comment lines `164` ~ `174` in `/Engine/SocketIO/Version1X.php`
> 
> then write this code
> 
> ```
> $protocol = true === $this->url['secured'] ? 'ssl' : 'http';
> 
> if(isset($this->context[$protocol])){
>     $context = $this->context;
>     $context['http']=$context[$protocol];
>     @unset($context['ssl']);
> }
> $context['http'] = $context['http'] ?? [];
> 
> if (isset($this->options['headers'])) {
>     $headers = $context[$protocol]['header'] ?? [];
>     $context['http']['header'] = array_merge($headers, $this->options['headers']);
> }
> if (isset($this->options['ssl'])) {
>     $ssl = $context[$protocol]['ssl'] ?? [];
>     $context['ssl'] = array_merge($ssl, $this->options['ssl']);
> }
> ```
 
I am using this code. How can I solve the problem?

$client = new Client(new Version2X('https://xxxxx:6001', 
    ['context' => 
        ['ssl' => 
            [
                'verify_peer_name' =>false, 
                'verify_peer' => false
            ]
        ]]
));

**Comment by berkturk** [comment]
https://stackoverflow.com/a/66090819/4690409

**Comment by andyfink** [comment]
What are u even talking about

**Comment by HirenViradia** [comment]
I am also facing same issue, I am not sure but I find out that if i use socket.io version 3.0.0 than I am getting connection error but when I am using version ^2.0.0 It is establish connection successfully.

**Comment by SeinopSys** [comment]
Since this package is largely unmaintained as far as I'm aware I've also stopped using it in my own app, and have not found a suitable replacement since.
