### ISSUE TITLE
Problems with empty frame

### ISSUE THREAD

**Issue by pavlefuture** [Wisembly/elephant.io#166]
Hello,

I have a strange error while trying to communicate via elephant.io client to external socket.io server.

I am able to connect to server, emit event, receive messages. However on every connection at some point (between 1 and 2min) I do get an empty frame which causes an error in:

```
AbstractSocketIO.php (line 126

(1/1) ErrorExceptionUndefined offset: 2
--
in AbstractSocketIO.php (line 126)
at Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined offset: 2', '/home/pavle/Laravel_projekti/crypto-price-collector/vendor/wisembly/elephant.io/src/Engine/AbstractSocketIO.php', 126, array('data' => '', 'bytes' => array()))in AbstractSocketIO.php (line 126)

) 
```

External server is on https. I am connecting using Version2X engine.

Any advice what could cause the issue?

**Comment by Taluu** [comment]
Hum, connections should not last that long, unless you are using it as a persistent connexion, which is currently not supported ?

**Comment by pavlefuture** [comment]
Wasn't aware of that. Thanks for the clarification

**Comment by Taluu** [comment]
My pleasure.

You're welcome to make a PR if you want to have a support. :}
