### ISSUE TITLE
Failing origins check, and using Version1X  when 2x is intended

### ISSUE THREAD

**Issue by yat0tv** [Wisembly/elephant.io#167]
My node socket has an origins requirement [e.g. io.set('origins', '');] but connection fails to meet that setting causing connection error

Fatal error: Uncaught exception 'ElephantIO\Exception\ServerConnectionFailureException' with message 'An error occurred while trying to establish a connection to the server' in /ElephantIO/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:187
Stack trace:
#0 /ElephantIO/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake()
#1 /ElephantIO/vendor/wisembly/elephant.io/src/Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect()
#2 /MM/includes/sockets.php(15): ElephantIO\Client->initialize()
#6 {main}
  thrown in /ElephantIO/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php on line 187

If remove the origins check I get this error

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The server returned an unexpected value. Expected "HTTP/1.1 101", had ""' in /ElephantIO/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:266
Stack trace:
#0 /ElephantIO/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(73): ElephantIO\Engine\SocketIO\Version1X->upgradeTransport()
#1 /ElephantIO/vendor/wisembly/elephant.io/src/Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect()
#2 /MM/includes/sockets.php(15): ElephantIO\Client->initialize()
#6 {main}
  thrown in /ElephantIO/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php on line 266

My code is

use ElephantIO\Client;
use ElephantIO\Engine\SocketIO\Version2X;
use ElephantIO\Exception\ServerConnectionFailureException;
require_once($_SERVER['DOCUMENT_ROOT'].'/ElephantIO/vendor/autoload.php');

class sockets{
    var $client;
    function connect(){
        $client = new Client(new Version2X('http://<mysite>:3133'));
        $client->initialize();
        $this->client = $client;
    }
}

**Comment by Taluu** [comment]
`http://:3133` does not seem right...

**Comment by yat0tv** [comment]
Oh sorry yes, I removed my url from the code as don't like to share urls. 
But in the running code there is a domain name in there I had put in a comment that I had removed but guess that got formatted out

**Comment by yat0tv** [comment]
any idea why it's erroring out on version 1 code when I'm setting it to use version 2?
