### ISSUE TITLE
fwrite(): SSL: Broken pipe error

### ISSUE THREAD

**Issue by dunky11** [Wisembly/elephant.io#183]
Hello, I currently get a warning if my connection was opened for too long. The below code works perfectly fine

    $socketIOClient = new Client(new Version2X('https://my-website.com:1337'));
    $socketIOClient->initialize();
    $socketIOClient->emit('pushMessageToSnackbar', ['message' => 'someMessage']);

However, if I sleep for more than around 1 minute, it gives me a warning and the message won't be emitted.

    $socketIOClient = new Client(new Version2X('https://my-website.com:1337'));
    $socketIOClient->initialize();
    sleep(80);
    $socketIOClient->emit('pushMessageToSnackbar', ['message' => 'someMessage']);

The warning:

    Warning: fwrite(): SSL: Broken pipe in /vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php on line 122

I got ubuntu 16.04 on my server.
Does somebody know how to fix that error?
Thanks for any help in advance!

**Comment by Taluu** [comment]
Elephantio doesn't support persistent connections. I think a ping on regular interval should do the trick.

**Comment by dunky11** [comment]
Ah okay, thank you really much. With a ping do you mean just an empty emit? And do you know which interval would be the best?

**Comment by Taluu** [comment]
You could do that, or maybe just renew the connection ? I was sure there was a `ping` method but I may have hallucinated it. :D

And no idea for the interval, sorry.

**Comment by dunky11** [comment]
```
$engine = new Version2X('my-website.com:1337');
$socketIOClient = new Client($engine);
$socketIOClient->initialize();

try {
  for ($i = 0; $i < 200; $i++) {
    if($i % 100 === 0) {
      $socketIOClient->emit('pushMessageToSnackbar', ['text' => 'hallo Welt!']);
      echo "pushedMessage";
    }
    sleep(2);
    $socketIOClient->getEngine()->keepAlive();
  }
} catch (Exception $e) {
  echo $e->getMessage();
}
```

Currently im doing this, but i get a 

`The action "SocketIO Version 2.X" is not supported by the engine "keepAlive"`

Do you know why?

**Comment by Taluu** [comment]
Try with the `dev-master` version. It seems I didn't release the keepAlive implementation (will try to do that when I'll have some time).

The message is wrong, I should also fix that.

**Comment by dunky11** [comment]
Thank you really much, changing composer to requiring "dev-master" instead of "^3.3.1" fixed the issue.
