### ISSUE TITLE
'Class 'ElephantIO\Client' not found'

### ISSUE THREAD

**Issue by juans0524** [Wisembly/elephant.io#184]
I installed this extension via composer and try to implement like a example included in the project; but when the init function on controller is called return this error: 'Class 'ElephantIO\Client' not found'. Here is my code:

```php
<?php

namespace backend\modules\mantenimiento\modules\listas\modules\sexo\controllers;
use Yii;
use backend\modules\mantenimiento\modules\listas\modules\sexo\models\Sexo;
use common\models\helpers\AccessHelper;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

use ElephantIO\Client, ElephantIO\Engine\SocketIO\Version1X;
require Yii::getAlias('@vendor'). '/autoload.php';


/**
 * ListasController implements the CRUD actions for TipoSede model.
 */
class SexoController extends Controller
{
    protected $socket;
    protected $pageSize;
    
    /**
     * Inisialisasi awal sebelum method dieksekusi.
     * @return void
     */
    public function init()
    {
        $this->socket = new Client(new Version1X("http://localhost:3000"));
            //new ElephantIo(new Version1X("http://localhost:8000"));
        $this->pageSize = 5;
    }
}
```

**Comment by peter279k** [comment]
@juans0524, thank you for your reply.

Could you format your sample code correctly?

You can use the "```php" to the beginning of same code and use "```" to the end of code,

**Comment by Taluu** [comment]
I edited the message. Could you check up in composer if the class is correctly registered ? Could you show your composer.json ?

**Comment by juans0524** [comment]
@Taluu, @peter279k : thank you for your reply. I found and solve the problem.
That problem was asociated with composer because, the composer setup was not loaded in the server; so the class doesnt exist. please close the issue and thanks again.
