### ISSUE TITLE
disconnect after some time

### ISSUE THREAD

**Issue by bazo** [Wisembly/elephant.io#19]
Hi,

i'm doing a long running import and send progress percentage to the browser. when the import reaches around 12% which is around 50s, the elephant client gets disconnected. There's no error, no message, just socket.io shows it was disconnected. the client is still sending messages happily, but they don't propagate to the browser.

i was pushing the progress every 1% of the import, then i doubled the frequency to 0.5% but everytime the import reached 12% it got disconnected.

is there a way how to catch this and reconnect?

**Comment by Taluu** [comment]
As it's been a while and the code has been rewritten from scratch, closing this issue
