### ISSUE TITLE
In Version1X.php line 194:  Notice: Undefined index: upgrades

### ISSUE THREAD

**Issue by Minirock** [Wisembly/elephant.io#192]
Hi,

I'm new to elephant io.
I've got a node server working.

I try to connect from my php Symfony project.

I've added the dependency using composer

    "wisembly/elephant.io": "~3.0"

But when I try to use it; I've got this undefined index: upgrades.
I don't know what does it mean.

Here is the piece of code

    use ElephantIO\Client;
    use ElephantIO\Engine\SocketIO\Version1X;

    $client = new Client(new Version1X('http://localhost:1299/map'));
        // open connection
        $client->initialize();

        $output->writeln("update des offres");
        $offers = $this->em->getRepository('AppRefactoredBundle:app_Offer')->findAll();
        foreach($offers as $offer){
            if($offer->getUpdatedAt() < new DateTime('-2 hours')){
                $offer->setCurrentStatus(2);

                // send for server (listen) the any array
                $client->emit('timeout', ['idUser' => $offer->getProfile()]);
            }
        }
    $client->close();

Looks like I'm missing something.

**Comment by peter279k** [comment]
@Minirock, thank you for your reply.

Is this `http://localhost:1299/map` a socket.io server?

I try reproducing the issue and run code you provide.

Could you provide this `socket.io` server version you run?

Thanks.

**Comment by Minirock** [comment]
@peter279k Thanks for helping. Yes it is.

Looks like this

    // Chargement du fichier index.html affiché au client
    var server = http.createServer(function(req, res) {
            fs.readFile('./ClientNotConnectedYet.html', 'utf-8', function(error, content) {
                res.writeHead(200, {"Content-Type": "text/html"});
                res.end(content);
            });
    });


    server.listen(1299);

    var io = require('socket.io').listen(server);


    //Roads
    const map = io.of('/map');


The html page here is not that important it's just in order to have something to reach in dev mode.

Here is the socket-io

    "socket.io": {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/socket.io/-/socket.io-2.2.0.tgz",
      "integrity": "sha512-wxXrIuZ8AILcn+f1B4ez4hJTPG24iNgxBBDaJfT6MsyOhVYiTXWexGoPkd87ktJG8kQEcL/NBvRi64+9k4Kc0w==",
      "requires": {
        "debug": "~4.1.0",
        "engine.io": "~3.3.1",
        "has-binary2": "~1.0.2",
        "socket.io-adapter": "~1.1.0",
        "socket.io-client": "2.2.0",
        "socket.io-parser": "~3.3.0"
      }
    }

**Comment by peter279k** [comment]
Hi @Minirock, thank you for your reply.

It seems that you use the `socket.io` version is `2.x`, but you use the `Version1X` client.

Try using the `Version2X` client to create establish connection.

Here is the [sample code](https://github.com/Wisembly/elephant.io/blob/master/example/socket.io/2.x/emitter-with-private-socket-id/client.php) about `Version2X` client.

Thanks.

**Comment by Minirock** [comment]
@peter279k Still the same error, I've replaced using Version 2.

        $client = new Client(new Version2X('http://localhost:1299/map')); 

But I still have the same error relative to version 1.

PS: I didn't added the header information I think I don't need them (or at least not now). But I don't understand how I reach an error in Version1X while I'm using the version2 :(

**Comment by peter279k** [comment]
Hi @Minirock, thank you for your reply.

After try reproducing issue, I found where the problem is.

Here is my sample code I execute.

`server.js`

```JS
var http = require('http');
var fs = require('fs');

var server = http.createServer(function(req, res) {
    fs.readFile('./ClientNotConnectedYet.html', 'utf-8', function(error, content) {
        res.writeHead(200, {"Content-Type": "text/html"});
        res.end(content);
    });
});

server.listen(1337);

var io = require('socket.io').listen(server);

//Roads
const map = io.of('/map');

```

`client.php`

```php
<?php
use ElephantIO\Client;
use ElephantIO\Engine\SocketIO\Version2X;

require __DIR__ . '/../../../../vendor/autoload.php';

$client = new Client(new Version2X('http://localhost:1337/map'));

$client->initialize();
$client->emit('broadcast', ['foo' => 'bar']);
$client->close();
```

After executing `client`, I also get the undefined `upgrade` index error.

And I print the result of response, I finally get the `ClientNotConnectedYet` HTML contents directly.

```HTML
string(290) "<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Not connected yet</h2>
</body>
</html>
"
```
I think the server you create doesn't seem to be a correct WebSocket server.

It looks like a HTTP server for me.

**Comment by Minirock** [comment]
Thanks, actually this is what I have in the html file

    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="/socket.io/socket.io.js"></script>
    <script>
        var socket = io.connect('http://localhost:1299/map');

        var information = {"idUser" : 2, "mode" : "0", "latitude": 50, "longitude" : 60, "codeCommune": 31400,"idPoint":1 };
        socket.emit('new', information);

    </script>

I just use it in order to simulate a connection in dev. But may be this is why I got this error even if I don't really understand why it would make an issue^^

**Comment by Minirock** [comment]
Looks like removing the html solved the issue. Not sure to understand why but it works.

**Comment by peter279k** [comment]
The WebSocket server will be expected to send response the JSON format, not `HTML` content.

I think you should know more knowledge about [WebSocket](https://en.wikipedia.org/wiki/WebSocket) protocol.

The `Content-Type` header is available for HTTP protocol, not for WebSocket.
