### ISSUE TITLE
oncesk/elephant.io for php7

### ISSUE THREAD

**Issue by asadkhalili** [Wisembly/elephant.io#206]
hi
i use https://github.com/oncesk/elephant.io
and after upgrade php to php 7 not working
error:
A non-numeric value encountered
 in /vendor/oncesk/elephant.io/lib/ElephantIO/Payload.phpat line 166
 ```
public function maskData($data, $key) {
        $masked = '';
 
        for ($i = 0; $i < strlen($data); $i++) {
            $masked .= $data[$i] ^ $key[$i % 4];
        }
 
        return $masked;
    }
```

please help me

**Comment by Taluu** [comment]
Please report that on the forked repo...
