### ISSUE TITLE
connection event not being called

### ISSUE THREAD

**Issue by quiquelhappy** [Wisembly/elephant.io#209]
Hello,
the library is showing it has been connected to the socket.io server successfuly, but when connecting or emitting, no event is called.

```js
const server = require('http').createServer();
const io = require('socket.io')(server);
io.on('connection', client => {
    console.log(client)
    client.on('foo', data => { console.log(data) });
    client.on('disconnect', () => { /* … */ });
});
server.listen(3000);
```

```php
<?php

use ElephantIO\Client;
use ElephantIO\Engine\SocketIO\Version2X;

require_once('./vendor/autoload.php');

$client = new Client(new Version2X('http://localhost:3000', []));

$client->initialize();
$client->emit('emit', ['foo' => 'bar']);
$client->close();
```

$client is being showed as connected after the initialize call, but it isnt actually connected according to the socket.io server. no exceptions are throwed

**Comment by quiquelhappy** [comment]
this is caused by using socket.io 3.x while using a 2.x client. related issue: https://github.com/Wisembly/elephant.io/issues/207

**Comment by Taluu** [comment]
Closing in favor of #207 then. Feel free to port your message over there.
