### ISSUE TITLE
Unexpected Response. Expected HTTP/1.1 101 got 1. Aborting...

### ISSUE THREAD

**Issue by gaecom** [Wisembly/elephant.io#38]
i run a node server listening to 8443.

it can work  using
$el=new Elephant("https://w.cc:8443", 'socket.io', 1, false, false, false);

it occured error  when i using 
$el=new Elephant("https://w.cc", 'socket.io', 1, false, false, false);

the error message is Unexpected Response. Expected HTTP/1.1 101 got 1. Aborting...

i got the returned message is HTTP/1.1 400 Bad Request

i've set reverse proxy in nginx.conf,in browser the code 
io.connect("https://w.cc") can run.

**Comment by Taluu** [comment]
As there are no response, closing this ticket (especially as the legacy branch is not really supported anymore)
