### ISSUE TITLE
Random exception: Socket.io did not send connect response. Aborting

### ISSUE THREAD

**Issue by folkenfanel** [Wisembly/elephant.io#44]
Hello. Great work. Thank you for sharing.

I'm experiencing random exceptions in emit calls. All browser connections was stable. Don't think it was a Node.JS or Socket.io client issue.

I'm using Node.js 10.26 and Socket.io 0.9.16.
I'm using sync disconnect on unload option enabled in Socket.io client.
All transports are enable in Node.js server: websocket, flashsocket, htmlfile, xhr-polling and jsonp-polling.

Any clue about this?

Best regards.

**Comment by Taluu** [comment]
Hello,

Have you tested with 3.0 ?

Cheers.
