### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by farukgaric** [Wisembly/elephant.io#45]
Hello all,

Thanks for this great tool. But developers need documentation for this. I have to solve some problems on our app and I try to use elephant.io first time but I don't know where to start. Can you help me? I just need some example how to setting up and how to combine my existing methods with e.io.

Thanks in advance!

**Comment by Taluu** [comment]
Closing, as this is superseeded by #105

**Comment by peckyboy** [comment]
I'm guessing the documentation has still not been worked on. Perhaps the library is dead as the website elephant.io is unreachable. Bummer.

**Comment by Taluu** [comment]
Reviewing PRs when there are some that makes sense, but yeah. We have a huge notice on the readme about that.

**Comment by peckyboy** [comment]
Thanks. Much appreciated.
