### ISSUE TITLE
How to implement the acknowledgement callback?

### ISSUE THREAD

**Issue by CowPanda** [Wisembly/elephant.io#58]
Hi,I want to implement the acknowledgement callback for the socket.io on my NodeJs Server, but elephant.io does not implement,what should i do?
Here is my question at stackoverflow [php socket.io Acknowledgement Callback?](http://stackoverflow.com/questions/25151859/php-socket-io-acknowledgement-callback)

**Comment by Taluu** [comment]
Closing, as this is an issue on 2.0, which is not maintained anymore
