### ISSUE TITLE
Socket.IO ip address

### ISSUE THREAD

**Issue by JanisGruzis** [Wisembly/elephant.io#77]
When i connect through elephant.IO to Socket.IO 1.x i cant find ip address of client:

<pre>
io.use(function(socket, next){
    var ip = socket.request.connection.remoteAddress;
    console.log(socket.request.connection.destroyed); // true
    console.log(ip); // undefined
});
</pre>

**Comment by Taluu** [comment]
Getting back on this error, I think I know why it doesn't work. Do you have `allow_url_fopen` activated ?

**Comment by JanisGruzis** [comment]
Yes.
