### ISSUE TITLE
Status of ssl connect in current version

### ISSUE THREAD

**Issue by eprincen2** [Wisembly/elephant.io#81]
I just upgraded versions of socket.io and elephant.io to the current versions and ported on my code to do things correctly. Everything works fine in http in development, but I have to use https in production. With https, socket.io works 100% fine js client / server, but elephant.io will not connect. Are there any current issues with ssl stream connects? The $host path looks correct going into the connect, so I'm wondering if any additional context info is missing. This all worked really well the old way (when init() existed.) ;-)

**Comment by brunobg** [comment]
I'm using https without any problems...

**Comment by Taluu** [comment]
Should be fixed by #103 (which still needs a full review and manual merging at the time this message is written)

**Comment by Zaszczyk** [comment]
@eprincen2 could You share You nodeJS code? This part exactly: I created a new http listener on my socket.io server and split client and server functions out. Clients still connect via SSL, and elephant.io connects without.
