### ISSUE TITLE
Multiple Variables (Like in Previous Versions)

### ISSUE THREAD

**Issue by lukepolo** [Wisembly/elephant.io#84]
Before we were able to separate the variables into parameters 

Example :

$elephant->emit('apend', array(array(1),'test', 'yay', 'test()'));

socket.on('append', function(user_ids, element, html, callback)
{
 // here you would get 
console.log(user_ids); // array(1);
console.log(element); // test
console.log(html); // yay
console.log(callback); // the function test()

}

I believe this functionality was taken out by mistake ?

**Comment by Lyricalz** [comment]
+1 for this, still can't do this with elephant, but can emit multiple params through normal socket.io
