### ISSUE TITLE
Can't connect to a server with SSL 

### ISSUE THREAD

**Issue by Bolandish** [Wisembly/elephant.io#90]
new ElephantIO\Client(new ElephantIO\Engine\SocketIO\Version1X('https://website.com:8000'));
Gives me a error

**Comment by Taluu** [comment]
Could you be more explicit ?

thanks

**Comment by thisispiers** [comment]
I get an error too:

exception 'ElephantIO\Exception\ServerConnectionFailureException' with message 'An error occurred while trying to establish a connection to the server'

**Comment by Taluu** [comment]
And does your server respond when trying to ping it ?

**Comment by thisispiers** [comment]
Well it's on localhost using self signed certificates

On Monday, 23 February 2015, Baptiste Clavié <notifications@github.com>
wrote:

> And does your server respond when trying to ping it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wisembly/elephant.io/issues/90#issuecomment-75659265>.
>


-- 

*Piers Simms*
c1h
www.c1h.co.uk

**Comment by Taluu** [comment]
The PR #95 should fix it. Can you test it ? Thanks
