### ISSUE TITLE
PHP syntax issue.

### ISSUE THREAD

**Issue by silverhawk184** [Wisembly/elephant.io#94]
In the file Client.php, lines 63 & 89 try to initiate an array with brackets. This gives me an error. Please update these to the proper array() function.

**Comment by guillaumepotier** [comment]
Hi there,

We deliberately chose not to support PHP <= 5.3 as our beloved language needs to go forward and support has been stopped for these versions.

I'm afraid we do not plan to use the old array syntax here. Feel free to fork the lib and replace them to support your PHP version.

Best
